### PR TITLE
feat(TPG >=4.51)!: add support for NAT tcp wait timeout

### PR DESCRIPTION
**Pull request by llavaud**
add support for the NAT `tcp_time_wait_timeout_sec` parameter

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by PascalBourdier — APPROVED** [review]

**Comment by PascalBourdier** [comment]
@bharathkkb @apeabody @morgante are you ok with that ?

**Comment by llavaud** [comment]
Hello,

**Comment by llavaud** [comment]
Hello,
@bharathkkb @apeabody @morgante Is there anything left to be done to get this PR merged ?

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @llavaud!

It looks like `tcp_time_wait_timeout_sec` was added in TPG 4.51.0.  Can you please bump https://github.com/terraform-google-modules/terraform-google-cloud-router/blob/master/versions.tf#L23

**Comment by llavaud** [comment]
> Thanks for the contribution @llavaud!
> 
> It looks like `tcp_time_wait_timeout_sec` was added in TPG 4.51.0. Can you please bump https://github.com/terraform-google-modules/terraform-google-cloud-router/blob/master/versions.tf#L23

done !

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @llavaud!

**Pull request merged**
